[config]
schemaVersion = "0.0.1"

[package]
namespace = "Quest_play"
name = "ColorLib"
versionNumber = "2.1.0"
description = "Color Library Mod"
websiteUrl = "https://github.com/Quest-play/ColorLib"
containsNsfwContent = false

[package.dependencies]

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./ReleaseOutput"
target = "./plugins/ColorLib"

[publish]
repository = "https://thunderstore.io"
communities = ["gatekeeper"]
categories = ["libraries"]